/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoIdRouteImport } from './routes/video.$id'
import { Route as PracticeIdIdxRouteImport } from './routes/practice.$id.$idx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIdRoute = VideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIdIdxRoute = PracticeIdIdxRouteImport.update({
  id: '/practice/$id/$idx',
  path: '/practice/$id/$idx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/video/$id': typeof VideoIdRoute
  '/practice/$id/$idx': typeof PracticeIdIdxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/video/$id': typeof VideoIdRoute
  '/practice/$id/$idx': typeof PracticeIdIdxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/video/$id': typeof VideoIdRoute
  '/practice/$id/$idx': typeof PracticeIdIdxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/video/$id' | '/practice/$id/$idx'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/video/$id' | '/practice/$id/$idx'
  id: '__root__' | '/' | '/video/$id' | '/practice/$id/$idx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VideoIdRoute: typeof VideoIdRoute
  PracticeIdIdxRoute: typeof PracticeIdIdxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$id': {
      id: '/video/$id'
      path: '/video/$id'
      fullPath: '/video/$id'
      preLoaderRoute: typeof VideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$id/$idx': {
      id: '/practice/$id/$idx'
      path: '/practice/$id/$idx'
      fullPath: '/practice/$id/$idx'
      preLoaderRoute: typeof PracticeIdIdxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VideoIdRoute: VideoIdRoute,
  PracticeIdIdxRoute: PracticeIdIdxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
